"""Culina cuisine ids, generated from the curation files in the Culina repo."""

CUISINES: dict[str, str] = {
    "afghan": "Afghan",
    "american": "American",
    "argentine": "Argentine",
    "austrian": "Austrian",
    "bangladeshi": "Bangladeshi",
    "belgian": "Belgian",
    "brazilian": "Brazilian",
    "british": "British",
    "bulgarian": "Bulgarian",
    "burmese": "Burmese",
    "cambodian": "Cambodian",
    "chilean": "Chilean",
    "chinese": "Chinese",
    "colombian": "Colombian",
    "cuban": "Cuban",
    "czech": "Czech",
    "danish": "Danish",
    "dominican": "Dominican",
    "dutch": "Dutch",
    "egyptian": "Egyptian",
    "ethiopian": "Ethiopian",
    "filipino": "Filipino",
    "finnish": "Finnish",
    "french": "French",
    "georgian": "Georgian",
    "german": "German",
    "ghanaian": "Ghanaian",
    "greek": "Greek",
    "haitian": "Haitian",
    "hawaiian": "Hawaiian",
    "hungarian": "Hungarian",
    "icelandic": "Icelandic",
    "indian": "Indian",
    "indonesian": "Indonesian",
    "irish": "Irish",
    "israeli": "Israeli",
    "italian": "Italian",
    "jamaican": "Jamaican",
    "japanese": "Japanese",
    "korean": "Korean",
    "laotian": "Lao",
    "lebanese": "Lebanese",
    "malaysian": "Malaysian",
    "mexican": "Mexican",
    "mongolian": "Mongolian",
    "moroccan": "Moroccan",
    "nepalese": "Nepalese",
    "nigerian": "Nigerian",
    "norwegian": "Norwegian",
    "pakistani": "Pakistani",
    "persian": "Persian",
    "peruvian": "Peruvian",
    "polish": "Polish",
    "portuguese": "Portuguese",
    "puerto_rican": "Puerto Rican",
    "romanian": "Romanian",
    "russian": "Russian",
    "senegalese": "Senegalese",
    "singaporean": "Singaporean",
    "south_african": "South African",
    "spanish": "Spanish",
    "sri_lankan": "Sri Lankan",
    "swedish": "Swedish",
    "swiss": "Swiss",
    "taiwanese": "Taiwanese",
    "thai": "Thai",
    "trinidadian": "Trinidadian",
    "tunisian": "Tunisian",
    "turkish": "Turkish",
    "ukrainian": "Ukrainian",
    "vietnamese": "Vietnamese",
}
